# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ash and Catherine
email: ashandcatherine@gmail.com
description: This is the site for our wedding
baseurl: ""
url: "http://ashandcatherine.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ashandcatherine

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
